export const RIDE_STATUS = {
  CREATED: 'CREATED',
  SEARCHING_DRIVER: 'SEARCHING_DRIVER',
  DRIVER_ASSIGNED: 'DRIVER_ASSIGNED',
  DRIVER_ARRIVING: 'DRIVER_ARRIVING', // Driver clicked "Arrived"
  ON_TRIP: 'ON_TRIP', // Driver clicked "Start Trip"
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
