export const RIDE_STATUS = {
  CREATED: 'CREATED',
  SEARCHING_DRIVER: 'SEARCHING_DRIVER',
  DRIVER_ASSIGNED: 'DRIVER_ASSIGNED',
  DRIVER_ARRIVED: 'DRIVER_ARRIVED',
  ON_RIDE: 'ON_RIDE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
